const resources = {
  en: {
    translation: {
      En: 'En',
      Uk: 'Uk',
      Main: 'Main',
      Membership: 'Membership',
      AboutUs: 'About us',
      Submit: 'Submit',
      NotFound: 'Ooops... Page not found',
      ErrorMessage: 'Ooops... You are getting an error',
      BackToMain: 'Back to main',
      Send: 'Send',
      Error: 'Error',
      HowItWas: 'How it was',
      Statut: 'Union charter',
      Directions: 'Directions',
      DirectSubtitle: 'which we promote in Ukraine',
      Join: 'Join',
      Contacts: 'Contacts',
    },
  },
  uk: {
    translation: {
      En: 'Анг',
      Uk: 'Укр',
      Main: 'Головна',
      Membership: 'Членство',
      AboutUs: 'Про нас',
      Submit: 'Підтвердити',
      NotFound: 'Упс... Сторінку не знайдено',
      ErrorMessage: 'Упс... Ви отримали помилку',
      BackToMain: 'Повернутися на головну',
      Send: 'Надіслати',
      Error: 'Помилка',
      HowItWas: 'Як це було',
      Statut: 'Cтатут спілки',
      Directions: 'Напрямки',
      DirectSubtitle: 'які ми просуваємо в Україні',
      Join: 'Долучитися',
      Contacts: 'Контакти',
    },
  },
};
export default resources;
