import type { Metadata } from 'next';
import StoreProvider from '@/lib/StoreProvider';
import ErrorBoundary from '@/components/error-boundary/error-boundary';
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';
import I18nProvider from '@/utils/launguages/launquage-provider';
import './globals.css';

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'hippotherapy',
  description: 'Generated by create next app',
  // icons: {
  //   icon: '/favicon.ico',
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {' '}
        <ErrorBoundary>
          <I18nProvider>
            <StoreProvider>
              <Header />
              {children}
              <Footer />
            </StoreProvider>
          </I18nProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
